In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv(r'C:\Users\hp\OneDrive - National University of Sciences & Technology\Desktop\spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [12]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [19]:
df['Spam'] = df['Category'].apply(lambda x:1 if x=='spam' else 0 )

In [20]:
from sklearn.model_selection import train_test_split

In [30]:
X_train,X_test,y_train,y_test = train_test_split(df.Message, df.Spam , test_size = 0.2)

In [31]:
X_train.shape

(4457,)

In [32]:
X_test.shape

(1115,)

In [33]:
type(X_test)

pandas.core.series.Series

In [34]:
X_train[:4]

3863                     Customer place, i wil cal u sir.
1787    Do you know why god created gap between your f...
2804                    FreeMsg>FAV XMAS TONES!Reply REAL
3831    I agree. So i can stop thinkin about ipad. Can...
Name: Message, dtype: object

In [36]:
y_train[:4]

3863    0
1787    0
2804    1
3831    0
Name: Spam, dtype: int64

# CountVectorizer is a tool from Scikit-learn used to convert text data into numerical feature vectors using the Bag of Words (BoW) model.

In [37]:
type(X_train.values)

numpy.ndarray

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)


In [46]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59552 stored elements and shape (4457, 7823)>

In [48]:
X_train_cv.shape

(4457, 7823)

In [50]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7823,))

In [51]:
v.get_feature_names_out()[10:30]

array(['02072069400', '02073162414', '02085076972', '021', '03', '04',
       '0430', '05', '050703', '0578', '06', '07', '07008009200',
       '07046744435', '07090201529', '07123456789', '07732584351',
       '07734396839', '07742676969', '07753741225'], dtype=object)

In [53]:
v.get_feature_names_out().shape
# This is our library

(7823,)

In [112]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [116]:
v.vocabulary_
# another way to find our library

{'customer': 2161,
 'place': 5269,
 'wil': 7597,
 'cal': 1635,
 'sir': 6257,
 'do': 2417,
 'you': 7787,
 'know': 4002,
 'why': 7584,
 'god': 3216,
 'created': 2100,
 'gap': 3123,
 'between': 1359,
 'your': 7792,
 'fingers': 2914,
 'so': 6353,
 'that': 6884,
 'one': 4977,
 'who': 7576,
 'is': 3795,
 'made': 4352,
 'for': 2993,
 'comes': 1945,
 'amp': 975,
 'fills': 2900,
 'those': 6933,
 'gaps': 3124,
 'by': 1625,
 'holding': 3516,
 'hand': 3360,
 'with': 7630,
 'love': 4273,
 'freemsg': 3042,
 'fav': 2846,
 'xmas': 7732,
 'tones': 7033,
 'reply': 5776,
 'real': 5654,
 'agree': 890,
 'can': 1665,
 'stop': 6570,
 'thinkin': 6919,
 'about': 774,
 'ipad': 3781,
 'please': 5291,
 'ask': 1124,
 'macho': 4345,
 'the': 6888,
 'same': 5960,
 'question': 5580,
 'have': 3404,
 'got': 3250,
 'radio': 5597,
 'times': 6975,
 'if': 3649,
 'not': 4868,
 'will': 7601,
 'get': 3167,
 'it': 3807,
 'now': 4882,
 'super': 6683,
 'da': 2177,
 'good': 3233,
 'replacement': 5772,
 'murali': 4690,
 'free': 303

In [58]:
X_train_np = X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4, 7823))

In [60]:
np.where(X_train_np[0]!=0)

(array([1635, 2161, 5269, 6257, 7597]),)

In [63]:
X_train[:4][1787]

'Do you know why god created gap between your fingers..? So that, One who is made for you comes &amp; fills those gaps by holding your hand with LOVE..!'

In [69]:
X_train_np[0][2804]

np.int64(0)

# now use ML Model

In [98]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [99]:
X_test_cv = v.transform(X_test)

In [100]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       968
           1       0.99      0.95      0.97       147

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [101]:
# model works well now test it on sample email

In [102]:
emails = [
    'hey, we have an evening football match at h-11 stadium.Please be on time',
    'Upto 20% discount on parking, exclusive offer just for u'
]
# the first email is not spam
# the second one is spam

In [103]:
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [104]:
# it works well

In [105]:
#using above though pipeline

In [106]:
from sklearn.pipeline import Pipeline

In [107]:
clf = Pipeline ([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [108]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [110]:
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       968
           1       0.99      0.95      0.97       147

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

